### ISSUE TITLE
error on launch

### ISSUE THREAD

**Issue by zeltak** [sainathadapa/i3-wm-multi-disp-scripts#1]
Hi and thx for these cool scripts

when i try to launch the create project script i get this:

`eltak@zx1voics:~/AUR/i3-wm-multi-disp-scripts|master                                                                                                      │14:19:09 INFO: [http://news.walla.co.il/item/3002099:10] %c
⇒  ./newProjectWorkspaces.py                                                                                                                               │14:19:09 INFO: [http://news.walla.co.il/item/3002099:11] [object HTMLImageElement]
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.                                                                             │14:19:10 ERROR: [http://isc.wcdn.co.il/w9/js/dfp/advertisers/messaging.min.js:2] Uncaught TypeError: Cannot set property 'onload' of null
Traceback (most recent call last):                                                                                                                         │14:19:12 WARNING: STUB: shutdown
  File "./newProjectWorkspaces.py", line 17, in <module>                                                                                                   │zeltak@zx1voics:~|⇒  qutebrowser --basedir "" --backend
    projectName = projectName.replace('\n', '').replace('\r', '')                                                                                          │zeltak@zx1voics:~|⇒  qutebrowser --basedir --backend webengine                                                                                              
TypeError: a bytes-like object is required, not 'str'                      
`

any clue?

**Comment by sainathadapa** [comment]
Can you check if you have `zenity` installed?

**Comment by zeltak** [comment]
Hi yes i have  zenity-3.20.0-1 

thx!

Z

**Comment by sainathadapa** [comment]
hmm, may be it is a python version issue? Can you try explicitly running the script with python 2.x version `python2 newProjectWorkspaces.py`

**Comment by zeltak** [comment]
sure here is the output with python2

```
zeltak@zx1voics:~/AUR/i3-wm-multi-disp-scripts|master                                                                                                      │zeltak@zx1voics:~|⇒  pulseaudio --kill && pulseaudio start
⇒  python2 newProjectWorkspaces.py                                                                                                                         │
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.                                                                             │E: [pulseaudio] main.c: Too many arguments.
Traceback (most recent call last):                                                                                                                         │zeltak@zx1voics:~|⇒  qutebrowser --basedir "" --backend webkit   
  File "newProjectWorkspaces.py", line 43, in <module>                                                                                                     │14:20:22 INFO: Zoom level: 110%
    commandToRun = commandToRun + 'workspace ' + currentOutputWK + '; '                                                                                    │14:20:22 INFO: Zoom level: 125%
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 30: ordinal not in range(128)         
```

**Comment by sainathadapa** [comment]
I made a small change to that script just now. Can you check if the error gets resolved with the new script. Run it with the python2.

**Comment by zeltak** [comment]
sure, updated the repo but still get errors:

```
zeltak@zx1voics:~/AUR/i3-wm-multi-disp-scripts|master                                                                                                      │libpng warning: iCCP: known incorrect sRGB profile
⇒  git pull                                                                                                                                                │libpng warning: iCCP: cHRM chunk does not match sRGB
remote: Counting objects: 3, done.                                                                                                                         │14:19:09 INFO: [http://news.walla.co.il/dist/scripts/vertical/wos/init.js?b=1475159131:2] walla_service: Version - V. 1.14
remote: Total 3 (delta 2), reused 2 (delta 2), pack-reused 1                                                                                               │14:19:09 INFO: [http://news.walla.co.il/item/3002099:10] %c
Unpacking objects: 100% (3/3), done.                                                                                                                       │14:19:09 INFO: [http://news.walla.co.il/item/3002099:11] [object HTMLImageElement]
From https://github.com/sainathadapa/i3-wm-multi-disp-scripts                                                                                              │14:19:10 ERROR: [http://isc.wcdn.co.il/w9/js/dfp/advertisers/messaging.min.js:2] Uncaught TypeError: Cannot set property 'onload' of null
   9116bb5..6cbb47b  master     -> origin/master                                                                                                           │14:19:12 WARNING: STUB: shutdown
Updating 9116bb5..6cbb47b                                                                                                                                  │zeltak@zx1voics:~|⇒  qutebrowser --basedir "" --backend
Fast-forward                                                                                                                                               │zeltak@zx1voics:~|⇒  qutebrowser --basedir --backend webengine                                                                                              
 newProjectWorkspaces.py | 3 ++-                                                                                                                           │zeltak@zx1voics:~|⇒  
 1 file changed, 2 insertions(+), 1 deletion(-)                                                                                                            │zeltak@zx1voics:~|⇒  qutebrowser --basedir --backend webengine                                                                                              
zeltak@zx1voics:~/AUR/i3-wm-multi-disp-scripts|master                                                                                                      │zeltak@zx1voics:~|⇒  pulseaudio --kill && pulseaudio start
⇒  python2 newProjectWorkspaces.py                                                                                                                         │
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.                                                                             │E: [pulseaudio] main.c: Too many arguments.
Traceback (most recent call last):                                                                                                                         │zeltak@zx1voics:~|⇒  qutebrowser --basedir "" --backend webkit   
  File "newProjectWorkspaces.py", line 46, in <module>                                                                                                     │14:20:22 INFO: Zoom level: 110%
    commandToRun = commandToRun.encode('utf-8') + 'workspace ' + currentWKName + '; '                                                                      │14:20:22 INFO: Zoom level: 125%
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 30: ordinal not in range(128)       
```

happy to help debugging this thx for your help!

z

**Comment by sainathadapa** [comment]
Can you check once again. It certainly seems like a utf-8 encoding problem. I am not using the right way that works across different systems. I changed the star to colon. This should work.

**Comment by zeltak** [comment]
yay that worked :)

now im trying to figure out how the scripts work Oo ;-)

would you consider doing a screencast at some point? i think it would help much in understanding the scripts :)

thx for all your work!

Z

**Comment by sainathadapa** [comment]
Good to know. I need to update the remaining scripts as well to remove instances of star in those. You may face difficulties with other scripts until i remove those. Sadly, I do not have access to a multiple monitor setup at this point, but I'll try to do a screencast sometime.

**Comment by sainathadapa** [comment]
I have now removed all instances of '★'. Let me know if you face any issues.
