### ISSUE TITLE
Error when creating new project

### ISSUE THREAD

**Issue by funsim** [sainathadapa/i3-wm-multi-disp-scripts#2]
When creating a new project, I get this error:

```bash
~/.i3/i3-project-focus-workflow git:master$ python newProjectWorkspaces.py 
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Traceback (most recent call last):
  File "newProjectWorkspaces.py", line 29, in <module>
    newWorkspaceNums = getValidWorkspaceNums(wkList, len(allOutputs))
  File "~/.i3/i3-project-focus-workflow/necessaryFuncs.py", line 19, in getValidWorkspaceNums
    return [goodWKNums[i] for i in range(0, num + 1)]
IndexError: list index out of range
```

**Comment by sainathadapa** [comment]
Can you post the output for the command `i3-msg -t get_workspaces`?

**Comment by funsim** [comment]
```
[{"num":2,"name":"2::PDEODE:2","visible":true,"focused":false,"rect":{"x":1920,"y":0,"width":1920,"height":1061},"output":"VGA1","urgent":false},{"num":7,"name":"7::SpringerBrief:2","visible":false,"focused":false,"rect":{"x":1920,"y":0,"width":1920,"height":1061},"output":"VGA1","urgent":false},{"num":8,"name":"8::W&D:2","visible":false,"focused":false,"rect":{"x":1920,"y":0,"width":1920,"height":1061},"output":"VGA1","urgent":false},{"num":0,"name":"0::W&D:1","visible":false,"focused":false,"rect":{"x":0,"y":0,"width":1920,"height":1181},"output":"DP1","urgent":false},{"num":1,"name":"1::PDEODE:1","visible":true,"focused":true,"rect":{"x":0,"y":0,"width":1920,"height":1181},"output":"DP1","urgent":false},{"num":6,"name":"6::SpringerBrief:1","visible":false,"focused":false,"rect":{"x":0,"y":0,"width":1920,"height":1181},"output":"DP1","urgent":false}]
```

**Comment by sainathadapa** [comment]
I pushed a bug fix, which should solve the issue. Can you try it out and let me know?

**Comment by funsim** [comment]
Works perfectly, thanks!

**Comment by funsim** [comment]
The issue occuered again:

```bash
~/.i3/i3-project-focus-workflow git:master$ python newProjectWorkspaces.py 
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Traceback (most recent call last):
  File "newProjectWorkspaces.py", line 39, in <module>
    currentWKName = str(newWorkspaceNums[i-1]) + ':' + wkNameProjectPart + str(i)
IndexError: list index out of range
```

```bash
~$ i3-msg -t get_workspaces
[{"num":2,"name":"2","visible":true,"focused":false,"rect":{"x":1920,"y":0,"width":1920,"height":1061},"output":"VGA1","urgent":false},{"num":1,"name":"1","visible":true,"focused":true,"rect":{"x":0,"y":0,"width":1920,"height":1181},"output":"DP1","urgent":false}]
```

**Comment by sainathadapa** [comment]
Sorry about that. Created a bug while fixing the previous one. Try now with the latest version.

**Comment by funsim** [comment]
Yep, works again.
